name: Push helm chart

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ['main']

env:
  REGISTRY: ghcr.io
  CHART_NAME: charts/${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish Helm chart to GHCR
        run: |
          helm package chart
          export CHART_VERSION=$(grep 'version:' ./chart/Chart.yaml | tail -n1 | awk '{ print $2 }')
          echo $CHART_VERSION
          helm push clippy-$CHART_VERSION.tgz oci://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          rm clippy-$CHART_VERSION.tgz
